#!/usr/bin/env bash
#  Bash script that accept 2 arguments {domain} and {subdomain} and the Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]


print_information () {
	local domain="$1"
	local subdomain="$2"
	local line=$(dig "$subdomain"."$domain" +short)
    
	echo "The subdomain $subdomain is a A record and points to $line"
}

if [ "$#" -eq 1 ]; then
	print_information "$1" "www"
	print_information "$1" "lb-01"
	print_information "$1" "web-01"
	print_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	print_information "$1" "$2"
fi
