#!/usr/bin/env bash
#  Bash script that accept 2 arguments {domain} and {subdomain} and the Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]


print_information ()
{
	line=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION:" | tr "\t" "\n" | tail -2 | tr "\n" " ")
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ "$#" -eq 2 ]; then
    print_information "$2.$1" "$2"
else
    print_information "www.$1" "www"
    print_information "lb-01.$1" "lb-01"
    print_information "web-01.$1" "web-01"
    print_information "web-02.$1" "web-02"
fi
