#!/usr/bin/env bash
#  Bash script that accept 2 arguments {domain} and {subdomain} and the Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]


print_information () {
	local domain="$1"
	local subdomain="$2"
	local line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
	echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}


if [ "$#" -eq 1 ]; then
    print_information "$1" "www"
    print_information "$1" "lb-01"
    print_information "$1" "web-01"
    print_information "$1" "web-02"
else
    print_information "$1" "$2"
fi
