#!/usr/bin/env bash
# Bash script that installs nginx
# and configure it to listen on port 80


sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
sudo nginx -t
echo -e "Hello World!" | dd status=none of=/var/www/html/index.html
sudo service nginx restart
