#!/usr/bin/env bash
# Bash script that installs nginx
# and configure it to listen on port 80


sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
