#!/usr/bin/env bash
# Configure a new Nginx server so that redirecting to another page


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/Mahmoud-Rehan/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
