#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.


sudo apt-get -y update
sudo apt-get -y install haproxy

server_config="
frontend cryptotechcoder
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server 460064-web-01 34.204.81.238:80 check
    server 460064-web-02 54.157.171.43:80 check
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg
sudo chown root:root /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
