#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid
# containing its PID

destroy() {
    rm /var/run/holbertonscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && destroy' SIGTERM
  trap 'destroy' SIGQUIT
done
