#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID

function destroy() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;destroy" SIGTERM
trap "echo Y U no love me?!;destroy" SIGINT

echo $$ >> /var/run/holbertonscript.pid

while [ true ]; do
    echo To infinity and beyond;
done
