#!/usr/bin/env bash
# Bash script that manages manage_my_process.

COMMAND="$1"


if [-z "$COMMAND" ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

if [ "$COMMAND" == "start" ]; then
	bash ./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "COMMAND" == "stop" ]; then
	[ -e "/var/run/my_process.pid" ] && pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$COMMAND" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}" 
fi
