#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

FILE="/etc/passwd"

while IFS=":" read -r user pass uid gid info dir cmd; do
  echo "The user $user is part of the $gid gang, lives in $dir and rides $cmd. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < $FILE
