#!/usr/bin/env bash
#  Bash script that loops from 1 to 10

NUM=0

while [ $NUM -lt 10 ]; do
	if [ $NUM -eq 3 ]; then
		echo bad luck
	elif [ $NUM -eq 7 ]; then
		echo good luck
	else
		echo Best School
	fi
	(( NUM++ ))
done		
