#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

HOUR=0
MINUTE=1

while [ $HOUR -le 12 ]; do
	echo Hour: $HOUR

	while [ $MINUTE -le 59 ]; do
		echo $MINUTE
		(( MINUTE++ ))
	done
	(( HOUR++ ))
	MINUTE=1
done
