#!/usr/bin/env bash
#  Bash script to install the ufw firewall and setup a few rules on web-01.


sudo apt update
sudo apt -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo 'y' | sudo ufw enable
